import {
  Document,
  Image,
  Page,
  Text,
  View,
  renderToBuffer,
} from "@react-pdf/renderer";
import React from "react";

import type { BrandProfile } from "@/lib/types";
import type { AccreditationWorkspaceData } from "@/lib/accreditation/types";
import { accreditationPdfStyles as styles } from "@/lib/accreditation/pdf-styles";
import { buildPdfFooter, normalizePdfBrand, type PdfBrand } from "@/lib/pdf/brand-export";
import { getEmbeddedLogo } from "@/lib/template-renderer/logo-data";

const ASCII_CONTROL_CHARACTERS = new RegExp(String.raw`[\u0000-\u001F]`, "g");

function sanitizer(value: string | undefined | null) {
  return (value ?? "").replace(ASCII_CONTROL_CHARACTERS, "").trim();
}

function formatWebsite(value: string) {
  if (!value) return "oleaconnects.ca";
  return value.replace(/^https?:\/\//, "").replace(/\/$/, "");
}

function BrandLogo({
  brand,
  logo,
  variant,
}: {
  brand: Pick<BrandProfile, "logoInitials" | "primaryColor" | "secondaryColor">;
  logo: ReturnType<typeof getEmbeddedLogo>;
  variant: "cover" | "header";
}) {
  const initials = sanitizer(brand.logoInitials || "OC").slice(0, 2).toUpperCase();

  if (logo?.dataUrl) {
    return (
      <Image
        src={logo.dataUrl}
        style={variant === "cover" ? styles.coverLogoImage : styles.headerLogoImage}
      />
    );
  }

  return (
    <View
      style={[
        variant === "cover" ? styles.coverLogo : styles.logo,
        { backgroundColor: brand.primaryColor || "#14532d" },
      ]}
    >
      <Text style={{ color: "#ffffff", fontSize: variant === "cover" ? 20 : 11 }}>
        {initials}
      </Text>
    </View>
  );
}

export async function renderAccreditationPdfBuffer(
  data: AccreditationWorkspaceData,
  brand: Partial<PdfBrand>,
) {
  const safeBrand = normalizePdfBrand(brand, "#14532d", "#dcfce7");
  const logo = getEmbeddedLogo(brand.logoUrl);
  const organizationName = sanitizer(
    safeBrand.organizationName || data.settings.organizationName || "Organization",
  );
  const reportTitle = "Accreditation Preparation Workspace";
  const preparedOn = new Date(data.lastUpdatedAt).toLocaleDateString("en-CA");
  const footerText = buildPdfFooter(safeBrand, reportTitle, preparedOn);

  const document = (
    <Document
      title={reportTitle}
      author={organizationName}
      subject="Accreditation preparation workspace generated by Olea Connects™"
      keywords="Olea Connects™, nonprofit governance, accreditation"
      creator="Olea Connects™"
      producer="Olea Connects™"
    >
      <Page size="LETTER" style={styles.cover}>
        <View style={[styles.coverLogo, { backgroundColor: safeBrand.primaryColor }]}>
          <BrandLogo brand={safeBrand} logo={logo} variant="cover" />
        </View>
        <View style={styles.coverContent}>
          <Text style={styles.coverEyebrow}>Accreditation workspace</Text>
          <Text style={[styles.coverTitle, { color: safeBrand.primaryColor }]}>
            {reportTitle}
          </Text>
          <View style={[styles.coverRule, { backgroundColor: safeBrand.secondaryColor }]} />
          <Text style={styles.coverOrg}>{organizationName}</Text>
          <Text style={styles.coverMeta}>Generated by Olea Connects™</Text>
        </View>
        <View style={styles.coverFooter}>
          <Text>{formatWebsite(brand.website || "oleaconnects.ca")}</Text>
          <Text render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
        </View>
      </Page>

      <Page size="LETTER" style={styles.page} wrap>
        <View style={[styles.accent, { backgroundColor: safeBrand.secondaryColor }]} fixed />
        <View style={styles.header} fixed>
          <View style={[styles.logo, { backgroundColor: safeBrand.primaryColor }]}>
            <BrandLogo brand={safeBrand} logo={logo} variant="header" />
          </View>
          <View style={styles.headerText}>
            <Text style={styles.headerOrg}>{organizationName}</Text>
          </View>
        </View>
        <Text style={styles.title}>{reportTitle}</Text>
        <Text style={styles.intro}>
          Prepared for {organizationName} on {preparedOn}. This summary captures the current completion status,
          key settings, and template progress for the accreditation preparation workspace.
        </Text>

        <View style={styles.section}>
          <Text style={styles.label}>Overview</Text>
          <View style={styles.row}>
            <Text style={styles.value}>Completion: {data.completionPercent}%</Text>
            <Text style={styles.chip}>{data.totals.completed}/{data.totals.total} templates complete</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.value}>Board approvals needed: {data.totals.boardApprovalNeeded}</Text>
            <Text style={styles.value}>Ready for board: {data.totals.readyForBoard}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.label}>Organization details</Text>
          <Text style={styles.value}>Organization: {data.settings.organizationName || organizationName}</Text>
          <Text style={styles.value}>Lead: {data.settings.leadName || "Not provided"}</Text>
          <Text style={styles.value}>Target date: {data.settings.targetDate || "Not provided"}</Text>
          <Text style={styles.value}>Charity number: {data.settings.charityNumber || "Not provided"}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.label}>Progress by section</Text>
          {data.sections.map((section) => (
            <View key={section.id} style={styles.row}>
              <Text style={styles.value}>{section.name}</Text>
              <Text style={styles.value}>{section.completed}/{section.total} complete</Text>
            </View>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.label}>Template status</Text>
          {data.responses.map((response) => {
            const template = data.templates.find((item) => item.code === response.templateId);
            return (
              <View key={response.templateId} style={{ marginBottom: 8 }}>
                <Text style={styles.value}>{template?.title ?? response.templateId}</Text>
                <Text style={styles.value}>{sanitizer(response.approvalStatus).replace(/_/g, " ")}</Text>
              </View>
            );
          })}
        </View>

        <View style={styles.footerRule} fixed />
        <Text
          fixed
          wrap={false}
          style={styles.footerText}
          render={({ pageNumber, totalPages }) => `${footerText} | Page ${pageNumber}/${totalPages}`}
        />
      </Page>
    </Document>
  );

  return renderToBuffer(document);
}
