import { StyleSheet } from "@react-pdf/renderer";

export const accreditationPdfStyles = StyleSheet.create({
  cover: {
    paddingTop: 60,
    paddingRight: 56,
    paddingBottom: 56,
    paddingLeft: 56,
    fontFamily: "Helvetica",
    color: "#1f2937",
    fontSize: 10,
  },
  coverLogo: {
    width: 76,
    height: 76,
    borderRadius: 12,
    color: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 20,
    fontFamily: "Helvetica-Bold",
  },
  coverLogoImage: {
    width: 64,
    height: 64,
    objectFit: "contain",
  },
  logo: {
    width: 34,
    height: 34,
    borderRadius: 8,
    color: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
  },
  headerLogoImage: {
    width: 28,
    height: 28,
    objectFit: "contain",
  },
  coverContent: {
    position: "absolute",
    left: 56,
    right: 56,
    bottom: 104,
  },
  coverEyebrow: {
    color: "#94a3b8",
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    letterSpacing: 1.6,
    marginBottom: 12,
    textTransform: "uppercase",
  },
  coverTitle: {
    fontSize: 32,
    fontFamily: "Helvetica-Bold",
    lineHeight: 1.15,
    maxWidth: 450,
  },
  coverRule: {
    width: 96,
    height: 4,
    borderRadius: 999,
    marginTop: 24,
    marginBottom: 24,
  },
  coverOrg: {
    fontSize: 17,
    fontFamily: "Helvetica-Bold",
    marginBottom: 8,
  },
  coverMeta: {
    color: "#64748b",
    fontSize: 12,
  },
  coverFooter: {
    position: "absolute",
    bottom: 34,
    left: 56,
    right: 56,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    flexDirection: "row",
    justifyContent: "space-between",
    color: "#94a3b8",
    fontSize: 9,
  },
  page: {
    paddingTop: 110,
    paddingRight: 42,
    paddingBottom: 96,
    paddingLeft: 42,
    fontFamily: "Helvetica",
    color: "#1f2937",
    fontSize: 10,
    lineHeight: 1.45,
  },
  accent: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 12,
  },
  header: {
    position: "absolute",
    top: 28,
    left: 42,
    right: 42,
    height: 48,
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  headerText: {
    marginLeft: 10,
    flexGrow: 1,
    height: 34,
    justifyContent: "center",
  },
  headerOrg: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: "#1f2937",
  },
  title: {
    fontSize: 24,
    fontFamily: "Helvetica-Bold",
    lineHeight: 1.2,
    marginBottom: 6,
  },
  intro: {
    fontSize: 11,
    color: "#4b5563",
    marginBottom: 22,
  },
  section: {
    marginTop: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 8,
  },
  label: {
    fontSize: 9,
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 1.2,
    marginBottom: 6,
  },
  value: {
    fontSize: 11,
    marginBottom: 8,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  chip: {
    fontSize: 10,
    color: "#14532d",
    backgroundColor: "#dcfce7",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    alignSelf: "flex-start",
  },
  footerRule: {
    position: "absolute",
    top: 735,
    left: 42,
    right: 42,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
  },
  footerText: {
    position: "absolute",
    top: 748,
    left: 42,
    right: 42,
    color: "#4b5563",
    fontSize: 7,
    textAlign: "center",
  },
});
